services:
  webport.erp.aspire:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    expose:
      - "18888"
      - "18889"
    networks:
      - "aspire"
    restart: "always"
  # postgres:
  #   image: "docker.io/library/postgres:17.6"
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
  #     POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  #   expose:
  #     - "5432"
  #   volumes:
  #     - type: "volume"
  #       target: "/var/lib/postgresql/data"
  #       source: "aspire-postgres-data"
  #       read_only: false
  #   networks:
  #     - "aspire"
  # cache:
  #   image: "docker.io/library/redis:8.2"
  #   command:
  #     - "-c"
  #     - "redis-server --requirepass $$REDIS_PASSWORD"
  #   entrypoint:
  #     - "/bin/sh"
  #   environment:
  #     REDIS_PASSWORD: "${CACHE_PASSWORD}"
  #   expose:
  #     - "6379"
  #   networks:
  #     - "aspire"
  webport-erp-api:
    image: "${WEBPORTERP_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${WEBPORTERP_PORT}"
      # ConnectionStrings__demo-db: "Host=postgres;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD};Database=demo-db"
      # ConnectionStrings__cache: "cache:6379,password=${CACHE_PASSWORD}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-docker-demo-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "WebportERP"
    expose:
      - "${WEBPORTERP_PORT}"
    # depends_on:
    #   postgres:
    #     condition: "service_started"
    #   cache:
    #     condition: "service_started"
    networks:
      - "aspire"
  # blazordashboard:
  #   image: "${BLAZORDASHBOARD_IMAGE}"
  #   environment:
  #     OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  #     OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  #     OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
  #     ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  #     HTTP_PORTS: "${BLAZORDASHBOARD_PORT}"
  #     OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-docker-demo-dashboard:18889"
  #     OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  #     OTEL_SERVICE_NAME: "BlazorDashboard"
  #   expose:
  #     - "${BLAZORDASHBOARD_PORT}"
  #   networks:
  #     - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  aspire-postgres-data:
    driver: "local"
