name: Webport.ERP.ASPIRE CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - development

jobs:
  build_images:
    name: Package Software
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/development'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      
      - name: Build and Push Docker Image using Docker Compose
        working-directory: ./docker-compose-artifacts
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/webport.erp.aspire
          TAG=$(echo $GITHUB_SHA | cut -c1-7) 
          docker compose -f docker-compose.yml build webport.erp.aspire
          docker compose -f docker-compose.yml push webport.erp.aspire         

  copy_files:
    name: Copy files to server
    runs-on: ubuntu-latest
    needs: build_images
    steps:
      - uses: actions/checkout@v4
      - name: Copy file via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: docker-compose-artifacts/docker-compose.yml
          target: /root/webport-system

  update_server:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: copy_files
    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/webport-system
            docker-compose -f docker-compose.yml stop webport.erp.aspire || true
            docker-compose -f docker-compose.yml rm -s -f webport.erp.aspire || true
            docker-compose -f docker-compose.yml pull webport.erp.aspire         
            docker-compose -f docker-compose.yml up -d webport.erp.aspire   
